## 3.1 Problem

You want to round a floating-point number to a fixed number of decimal places.
- For simple rounding, use the built-in round(value, ndigits) function. 
- When a value is exactly halfway between two choices, the behavior of round is to round to the nearest even digit. That is, values such as 1.5 or 2.5 both get rounded to 2.
- if floating number is part of a string use format instead of round


In [1]:
# round 123456.98765
x = 123456.98765

print('x:', x)
print('round(x,2): ',round(x,2))
print('round(x,5): ',round(x,5))
print('round(x,6): ',round(x,6))
print('round(x,-1): ',round(x,-1))
print('round(x,-4): ',round(x,-4))
print('round(x,-7): ',round(x,-7))
print('format(x, 0.2f):',format(x, '0.2f'))

x: 123456.98765
round(x,2):  123456.99
round(x,5):  123456.98765
round(x,6):  123456.98765
round(x,-1):  123460.0
round(x,-4):  120000.0
round(x,-7):  0.0
format(x, 0.2f): 123456.99


#### 3.2 Problem

You need to perform accurate calculations with decimal numbers, and don’t want the
small errors that naturally occur with floats.

- A well-known issue with floating-point numbers is that they can’t accurately represent all base-10 decimals. Moreover, even simple mathematical calculations introduce small errors.
- If you want more accuracy (and are willing to give up some performance), you can use the decimal module:
- If you print them or use them in string formatting functions, they look like normal numbers.
- A major feature of decimal is that it allows you to control different aspects of calculations, including number of digits and rounding. To do this, you create a local context and change its settings.
- Mostly used. in finance
- Even though float is not as accurate as the decimal module it is. more commonly used because its faster and most things that small difference can represent randomness as it is impossible to capture something at such a. precisison.

In [2]:
a = 4.2
b = 2.1
print('a+b=', a+b)

from decimal import Decimal,localcontext

a2 = Decimal('4.2')
b2 = Decimal('2.1')

print('a2+b2=', a2+b2)

a2 = Decimal('1.3')
b2 = Decimal('1.7')

print('a2/b2 : ',a2 / b2)

with localcontext() as lc:
    lc.prec = 3
    print('a2/b2 lc(): ',a2 / b2)

a+b= 6.300000000000001
a2+b2= 6.3
a2/b2 :  0.7647058823529411764705882353
a2/b2 lc():  0.765


### 3.3 Problem

You need to format a number for output, controlling the number of digits, alignment,
inclusion of a thousands separator, and other details.

- format() f-float ,  e-exponential notation
    - '>' (right justified)
    - < (left justified)
    - ^ center
    - , (thousand seperator)
    - <float/>f (precision to the floating number)

- The general form of the width and precision in both cases is '[<>^]?width[,]?(.digits)?' where width and digits are integers and ? signifies optional parts. The sameformat codes are also used in the .format()
    

In [3]:
x = 123456.98765

print('x: ',x)
print('>: ',format(x,'>10.1f'))
print('<: ',format(x,'<10.1f'))
print('^: ',format(x,'^10.1f'))
print(',: ',format(x,'0,'))
print(',f: ',format(x,'0,.2f'))
print('e: ',format(x,'1e'))

x:  123456.98765
>:    123457.0
<:  123457.0  
^:   123457.0 
,:  123,456.98765
,f:  123,456.99
e:  1.234570e+05


## 3.4 Problem

You need to convert or output integers represented by binary, octal, or hexadecimal digits.

- functions (bin(),oct()hex())
- format (b - bin , o - oct, x - hex format(<num/>, car)
- signed by default, to unsign set the bit length i.e. : 2**<bit-size>


In [4]:
x = 255

print('x ',x)
print('bin(x): ', bin(x))
print('oct(x): ', oct(x))
print('hex(x): ', hex(x))
print('format(x, b)',format(x, 'b'))
print('format(x, o)',format(x, 'o'))
print('format(x, x)',format(x, 'x'))
print('format(2**32 + x, x)',format(2**32 + x, 'x'))

x  255
bin(x):  0b11111111
oct(x):  0o377
hex(x):  0xff
format(x, b) 11111111
format(x, o) 377
format(x, x) ff
format(2**32 + x, x) 1000000ff


#### 3.5 Problem
You have a byte string and you need to unpack it into an integer value. Alternatively, you need to convert a large integer back into a byte string.

- int.from_byte()
- int.to_byte()

In [5]:
x = 2131332
print('x',x)
x2 = x.to_bytes(16,'big')
print('x to.bytes(16,big)', x2)
x3 = x.to_bytes(16,'little')
print('x to.bytes(16,big)', x3)

print('int.from_bytes(x2,big): ', int.from_bytes(x2,'big'))
print('int.from_bytes(x3,liitle): ', int.from_bytes(x3,'little'))
print('int.from_bytes(x3,big):', int.from_bytes(x3,'big'),'*Notice a diff key == different results')

x 2131332
x to.bytes(16,big) b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x85\x84'
x to.bytes(16,big) b'\x84\x85 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
int.from_bytes(x2,big):  2131332
int.from_bytes(x3,liitle):  2131332
int.from_bytes(x3,big): 176149319962901344151350654280832909312 *Notice a diff key == different results


#### 3.6 Problem
Your code for interacting with the latest web authentication scheme has encountered a singularity and your only solution is to go around it in the complex plane. Or maybe you just need to perform some calculations using complex numbers.

- complex function ... complex(real,imag)
- a = complex(x,i)-> a.real = x , a.imag=i
-



In [6]:
import cmath
a = 3 + 2j

# b = 3 + 2l VARIABLE HAS TO BE J

print('a',a)
print('a.real',a.real)
print('a.imag',a.imag)
print('a + 2', a + 2)
print('a-4j', a-4j)
print('sin a', cmath.sin(a))

a (3+2j)
a.real 3.0
a.imag 2.0
a + 2 (5+2j)
a-4j (3-2j)
sin a (0.5309210862485197-3.5905645899857794j)


#### 3.7 Problem
You need to create or test for the floating-point values of infinity, negative infinity, or NaN (not a number).

-float('inf'), float('-inf'), float('nan')
- inf will operate as if its a normal num
- nan will not appear as ==
- only way to test if ther is an nan is to use math.isnan()

In [7]:
print('float(inf)',float('inf'))
print('float(-inf)',float('-inf'))
print('float(nan)',float('nan'))

float(inf) inf
float(-inf) -inf
float(nan) nan


#### 3.8 Problem
You have entered a time machine and suddenly find yourself working on elementary- level homework problems involving fractions. Or perhaps you’re writing code to make calculations involving measurements made in your wood shop

- Fraction module 
- import Fraction from fractions
- convert fraction to float float()
- convert float to fraction -> Fraction(<float/>.as_integer_ratio()) ** Doesnt work without the *, why?

In [8]:
from fractions import Fraction

In [9]:
a = Fraction(5,3)
b = Fraction(53,13)
print('a',a)
print('b',b)
print('a+b: ', a + b)
print('a numerator ', a.numerator)
print('b denominator', b.denominator)
print('a as float', float(a))
c = a * b
print('c = a * b:', c)
print('c.numerator', c.numerator)
print('c.denominator', c.denominator)
print('c.limit_denomerator', c.limit_denominator(7))
d = float(4.45)
print('d',d)
print('Fraction(d.as_integer_ratio())',Fraction(*d.as_integer_ratio()))





a 5/3
b 53/13
a+b:  224/39
a numerator  5
b denominator 13
a as float 1.6666666666666667
c = a * b: 265/39
c.numerator 265
c.denominator 39
c.limit_denomerator 34/5
d 4.45
Fraction(d.as_integer_ratio()) 5010254585449677/1125899906842624


#### Problem
You need to perform calculations on large numerical datasets, such as arrays or grids.

- cant do some basic algorithics with arrays and numbers
- multiply an array dont multilplt the elements it multiply the actual array 
- adding adds array a to array b
- to solve this we use numpy
- numpy as univeral funct such as sqrt and cos
- sub region can be array[[]] [x:y,a:b] ~ not inclusive


In [28]:
a= [1,2,3,4,5]
b= [11,12,13,14,15]

print('a: ',a)
print('a * 2: ',a*2)
print('a+b: ',a+b)
import numpy as np
ax = np.array(a)
bx = np.array(b)
print('ax = np a', ax)
print('bx = np b', bx)
print('ax * 2:', ax * 2)
print('bx + 10', bx + 10)
print('ax * bx', ax * bx)
print('ax cos', np.cos(ax))
print('bx sqrt', np.sqrt(ax))
cx = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('cx:\n', cx)
print('cx[1]:', cx[1])
print('cx[:,1]',cx[:,1])
print('cx: reprint\n', cx)
print('cx[1:3,:]', cx[1:3,:])


a:  [1, 2, 3, 4, 5]
a * 2:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
a+b:  [1, 2, 3, 4, 5, 11, 12, 13, 14, 15]
ax = np a [1 2 3 4 5]
bx = np b [11 12 13 14 15]
ax * 2: [ 2  4  6  8 10]
bx + 10 [21 22 23 24 25]
ax * bx [11 24 39 56 75]
ax cos [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
bx sqrt [1.         1.41421356 1.73205081 2.         2.23606798]
cx:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
cx[1]: [4 5 6]
cx[:,1] [2 5 8]
cx: reprint
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
cx[1:3,:] [[4 5 6]
 [7 8 9]]


### 3.10 Problem
You need to perform matrix and linear algebra operations, such as matrix multiplication, finding determinants, solving linear equations, and so on.

- multiply by a vector
- when multiplying order does matter, vec

In [39]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print('a:\n',a)
print('a.T:\n',a.T)
# print('a.i:\n',a.I)
av = np.matrix([[2],[3],[1]])
print('av:\n', av)
print('av * a:\n', a * av)

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a.T:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
av:
 [[2]
 [3]
 [1]]
av * a:
 [[11]
 [29]
 [47]]


### Lab Reflection

In this Lab i learned a lot of things. One thing i learned was that the round function rounds to the nearest even digit. As much as i used the round method in my coding career that particular information was new to me and interesting now that i think about it. i also found it interesting that float does not return the precise number  that is being added, i actually found it more interesting that most studies that you would thing would want an accurate representation of data but they actually like to keep that room for error. 

Overall i believe this section gave me a better understanding of numbers being more than numbers you can count.Many different studies may require a number to be represented a different way. For an example a finance firm may want a more accurate and precise representation of a number while scientist want the same number dont mind giving up the computational power and settling for a less precise number.

Numbers can be complex meaning having imaginary numbers, numbers can be in a fraction form, numbers can in a matrix which allows you to manipulate a big list of number at once and in different dimensions. In python numbers can be converted into bytes,hex,and octs with just a call to a function making it easy to convert the representation of a number.